### ISSUE TITLE
New user access

### ISSUE THREAD

**Issue by Joshuaalbert** [ovro-lwa/calim-ops#1]
Rick or Kemby here's my user request. @caseyjlaw

username: `albert`

Here's my public key:
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZqHaCi4HZjrLUQErh5BeiwcZ9BJpUW1AREFlupeEkgSAZrWSqFKyT15LoJCTijnIkQ+CyJlf9k1LfUQ34QqT1zqecnJSdrpFxiWvB3vleGVTJRDQIhnFaMNhr7cPN1Mp7UzmBgIyhno0rkMcPgiRhHrph/ab2orVOb14gCJL1rHoAIqqXgJXxtZ4Ewk2Kfv3gBz+TyPjHtICoGvQnEKDgtGHV8faQT4+nZQD8OLOfdhI9A6CnmecdKrEoX+1Ofeea0nAEn7Lzop6iv4II5qA3/+U1upjTzR9Ih679OdgfyJO0+enb2wa0uBqqdLnDnpXHSqOOGC1e3e0i4ZKnstNR albert@geleen.strw.leidenuniv.nl
```

**Comment by caseyjlaw** [comment]
Hi @kembyct. This request is part of a sprint project this week for OVRO-LWA. Could you get Josh set up on ssh.ovro.caltech.edu and lwacalim as soon as possible?

**Comment by kembyct** [comment]
Hello @caseyjlaw 
For some reasons, I just get to see your email today. I wonder if it's been taking care of. sorry about that.

**Comment by caseyjlaw** [comment]
not yet. it is a high priority though!

**Comment by kembyct** [comment]
It's been complete!

-Kemby
________________________________

**Comment by Joshuaalbert** [comment]
Hi @kembyct I only seem to have gateway access, so I can get to lwamaas, but not any further.

**Comment by yupinghuang** [comment]
@Joshuaalbert try again? If you could post the commands you used from lwamaas, that'd be helpful.

**Comment by Joshuaalbert** [comment]
Hi @yupinghuang, tried these
```
ubuntu@lwamaas:~$ ssh albert@lwacalim00
```
```
ubuntu@lwamaas:~$ ssh albert@lwacalim00.mcs.pvt
```

**Comment by yupinghuang** [comment]
I assume it asks for a password when you did that.

It...should've work -- LDAP is showing the right fingerprint, but I stuck the key in `authorized_keys` for good measure.

I assume that agent-forwarding is enabled and you did `ssh -A lwamaas`?

Run a `ssh-add -l` and send along the output on `lwamaas` if it still doesn't work. Also if you could paste the output from `ssh -v albert@lwacalim00`, that'd be great.

**Comment by Joshuaalbert** [comment]
I only provided my public key, so I don't know the password. Prefer to keep passwords to a minimum anyways for security.

**Comment by yupinghuang** [comment]
- "I assume it asks for a password when you did that."
I meant that's what I assumed to have happened when you tried ssh'ing into lwacalim00. I wasn't implying that a password is needed.

The rest of my comment still applies.

**Comment by Joshuaalbert** [comment]
Resolved! Thanks for the help
